"""Initial schema

Revision ID: 464c9b05374b
Revises:
Create Date: 2026-02-17 00:43:09.393153

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "464c9b05374b"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "models",
        sa.Column("model_id", sa.String(length=255), nullable=False),
        sa.Column("adapter_type", sa.String(length=50), nullable=True),
        sa.Column("location", sa.String(length=50), nullable=True),
        sa.Column("model_metadata", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("model_id"),
    )
    op.create_table(
        "experiments",
        sa.Column("experiment_id", sa.String(length=255), nullable=False),
        sa.Column("model_a_id", sa.String(length=255), nullable=True),
        sa.Column("model_b_id", sa.String(length=255), nullable=True),
        sa.Column("probability_split", sa.Float(), nullable=True),
        sa.Column("metric_type", sa.String(length=50), nullable=True),
        sa.Column("confidence_level", sa.Float(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["model_a_id"],
            ["models.model_id"],
        ),
        sa.ForeignKeyConstraint(
            ["model_b_id"],
            ["models.model_id"],
        ),
        sa.PrimaryKeyConstraint("experiment_id"),
    )
    op.create_table(
        "requests",
        sa.Column("request_id", sa.String(length=255), nullable=False),
        sa.Column("experiment_id", sa.String(length=255), nullable=True),
        sa.Column("model_variant", sa.String(length=10), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.Column("request_metadata", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["experiment_id"],
            ["experiments.experiment_id"],
        ),
        sa.PrimaryKeyConstraint("request_id"),
    )
    op.create_index(
        "idx_experiment_timestamp",
        "requests",
        ["experiment_id", "timestamp"],
        unique=False,
    )
    op.create_table(
        "outcomes",
        sa.Column("request_id", sa.String(length=255), nullable=False),
        sa.Column("value", sa.Float(), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["request_id"],
            ["requests.request_id"],
        ),
        sa.PrimaryKeyConstraint("request_id"),
    )
    op.create_index("idx_request_id", "outcomes", ["request_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_request_id", table_name="outcomes")
    op.drop_table("outcomes")
    op.drop_index("idx_experiment_timestamp", table_name="requests")
    op.drop_table("requests")
    op.drop_table("experiments")
    op.drop_table("models")
    # ### end Alembic commands ###
